version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app
    ports:
      - "8000:8000"
  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_DB=case_challenge
      - POSTGRES_USER=case_challenge
      - POSTGRES_PASSWORD=case_challenge
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

volumes:
  postgres_data: