version: '3.8'

services:
  db:
    build: case_challenge/infra/db/docker/
    environment:
      - POSTGRES_MULTIPLE_DATABASES=db_case_challenge,test_case_challenge
      - POSTGRES_USER=case_challenge
      - POSTGRES_PASSWORD=case_challenge
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app
    ports:
      - "8001:8000"
volumes:
  db_data: